[package]
name = "mezon-updater"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
url.workspace = true
semver.workspace = true
sha2.workspace = true
base64.workspace = true
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
which.workspace = true
