[package]
name = "mezon-store"
version.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
mezon-client.workspace = true
mezon-proto.workspace = true
mezon-i18n.workspace = true
mmn-client.workspace = true
mezon-updater.workspace = true
mezon-voice.workspace = true
mezon-audio.workspace = true
gpui.workspace = true
image = { workspace = true, features = ["webp"] }
smallvec.workspace = true
parking_lot.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
dirs.workspace = true
flume.workspace = true
url.workspace = true
tokio.workspace = true
prost.workspace = true
regex.workspace = true
